version: "3.7"

services:
  database:
    image: postgres
    container_name: post-compose
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=node-docker
    volumes:
      - pgdata:/data/postgres
    network_mode: host
  app:
    build: .
    container_name: node-docker
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    network_mode: host

volumes:
  pgdata:
    driver: local
